spring:
  application:
    name: attendee-checkin-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/checkin_db;MODE=PostgreSQL;AUTO_SERVER=TRUE}
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8086

springdoc:
  swagger-ui:
    path: /swagger-ui.html

checkin:
  allow-duplicate-audit: false